### ISSUE TITLE
Merge into master to-do list

### ISSUE THREAD

**Issue by danieljfarrell** [danieljfarrell/pvtrace#12]
- [x] Merge into `pvtrace2` branch
- [x] Add issues for new features:
    - [x] coatings
    - [x] rod geometry
    - [x] more efficient box geometry
    - [x] improved LSC example script
    - [x] constructive solid geometry of nodes
- [x] write readme.md
- [x] Connect to readthedocs
- [x] Test that we can make a working install using setup.py and requirement.txt in a fresh virtualenv
- [x] Merge pvtrace2 branch to master (i.e. finalise github side of things)
- [x] Update the pypi package to point to images in github repo or imgur.
- [x] Upload to pypi
- [x] Test install from pypi
- [ ] Get working with conda and upload conda environment.yml
- [ ] Upload as conda package (windows/mac)
- [ ] Write instruction for setting up development environment using pyenv (Mac/Linux)
